### ISSUE TITLE
Suppose to be 1v1?

### ISSUE THREAD

**Issue by MisterHarper** [Toly65/UdonCombatSystem#12] opened 2022-04-22 07:14 UTC
Hello Toly65,

Everything in the project is working as I believe you intended. The only thing I wasn't sure about is the amount of people able to play together. A friend and I tested together and we could fight just fine in a 1v1. So we went on to test it out with more people. We prepared to do a 3v3 but instantly ran into a issue. 

- Out of the 6 of us there was only 2 that could be killed. 
- They could shoot each other still.
- The other 4 could pick up weapons and shoot them, but the 4 could not be killed.

I don't know if this is something wrong done on my side or if its only setup for a 1v1 at this time. Thank you in advance for the work you have done in this project. We have been having a lot of fun with it.

**Comment by Toly65** [comment] 2022-04-22 08:51
it's designed for up to 80 people,

<img width="854" alt="image" src="https://user-images.githubusercontent.com/88860967/164658813-847d1770-c1e6-4c66-8225-0004a4739671.png">
check these hitboxes and make sure they have everything assigned, sometimes changing the damage modifier on the sub hitboxes (shown in pic) can alleviate the issue,

the first hitbox is always assigned to the local player, if you make change to one you must delete all of the others, clone the modified ones and give them to the hitbox manager
if you are doing this I would recommend you would look at this, as it's easier to fill the array with this knowledge
https://answers.unity.com/questions/689126/quickly-assigning-to-array-in-editor.html

**Comment by MisterHarper** [comment] 2022-04-22 17:44
![image_2022-04-22_102535628](https://user-images.githubusercontent.com/104182613/164764247-773c6d02-2c4b-4b9e-8b6b-a53bff2808d1.png)

I went through the ImprovedHitbox and made sure everything had its proper scripts. I still had the same issue of only 2 people able to die. Then I did as you said and changed the Damage modifier inside hitbox head and created new duplicates and placed them in the hitbox manager. This still ended with the same result. 

Thank you for the quick response.

**Comment by Toblerony** [comment] 2022-05-28 13:57
Hey 
I am having similar issues. it seems to be happening with no real consistency, I have also tried replacing all the hit boxes ect but still having the same issues with some players becoming immortal

**Comment by Toly65** [comment] 2022-05-28 14:12
hitbox assigning is being redone in this update, it may possibly fix the immortality bug as it makes sure things are assigned properly, as the cause of the bug is still unknown I can't guarantee a fix

**Comment by Toblerony** [comment] 2022-05-30 05:10
Awesome hopefully it does ;D 

I for the life of me cant figure out why it happens though. 
Like op mentioned it only happens when you have more than 2 players, and seems to only effect the world host?. when you change the world host the immortal player also changes. they cant take or deal dmg

**Closed** 2022-11-01 21:39 UTC
